#!/bin/sh
### BEGIN INIT INFO
# Provides:          np30-controller application
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       np30-controller application
### END INIT INFO

WORKING_DIR=/home/pi/np30-controller
SERVICE_NAME=np30-controller
SCRIPT=start-np30-controller.sh
RUNAS=pi

PIDFILE=$WORKING_DIR/np30-controller.pid
LOGFILE=$WORKING_DIR/np30-controller.log

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo "Service $SERVICE_NAME already running" >&2
    return 1
  fi
  echo "Starting service $SERVICE_NAME" >&2
  local CMD="$WORKING_DIR/$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo "Service $SERVICE_NAME started" >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo "Service $SERVICE_NAME not running" >&2
    return 1
  fi
  echo "Stopping service $SERVICE_NAME" >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo "Service $SERVICE_NAME stopped" >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
